ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS qr_payload TEXT;
ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS qr_uri TEXT;
ALTER TABLE booking_seats ADD COLUMN IF NOT EXISTS redeemed BOOLEAN DEFAULT FALSE;
